# Generated by Django 3.0.7 on 2020-06-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Content',
            new_name='content',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='ulr',
            field=models.URLField(default='http://localhost:8000/blog/'),
        ),
    ]
