# Generated by Django 3.0.7 on 2020-06-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200611_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='ulr',
        ),
    ]
